version: '2'

networks:
  bibbox-default-network:
    external: true

services:

  $$INSTANCE-baobab:
    image: bibbox/baobab
    container_name: $$INSTANCE-baobab
    restart: unless-stopped
    networks:
      - bibbox-default-network
    depends_on:
      - $$INSTANCE-bika

  $$INSTANCE-bika:
    image: bika
    container_name: $$INSTANCE-bika
    restart: unless-stopped
    networks:
      - bibbox-default-network
    ports:
          - "$$PORT:8080"
    links:
      - $$INSTANCE-baobab:baobab
